-- MySQL Script generated by MySQL Workbench
-- Sun Jun  3 01:50:48 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`imagenes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`imagenes` (
  `idImagenes` INT NOT NULL AUTO_INCREMENT,
  `imagen` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idImagenes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuarios` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `contraseña` VARCHAR(45) NOT NULL,
  `fkIdImagenes` INT NOT NULL,
  PRIMARY KEY (`idUsuario`),
  INDEX `fk_usuarios_imagenes1_idx` (`fkIdImagenes` ASC),
  CONSTRAINT `fk_usuarios_imagenes1`
    FOREIGN KEY (`fkIdImagenes`)
    REFERENCES `mydb`.`imagenes` (`idImagenes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`proyectos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`proyectos` (
  `idproyecto` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NULL,
  `descripcion` VARCHAR(255) NULL,
  `fechaInicio` DATETIME NOT NULL,
  `fechaFin` DATETIME NULL,
  `fkIdUsuario` INT NOT NULL,
  PRIMARY KEY (`idproyecto`),
  INDEX `fk_proyectos_usuarios1_idx` (`fkIdUsuario` ASC),
  CONSTRAINT `fk_proyectos_usuarios1`
    FOREIGN KEY (`fkIdUsuario`)
    REFERENCES `mydb`.`usuarios` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`documntos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`documntos` (
  `idDocumento` INT NOT NULL AUTO_INCREMENT,
  `documento` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idDocumento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tareas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tareas` (
  `idtarea` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(500) NOT NULL,
  `fechaInicio` DATETIME NOT NULL,
  `fechaFin` DATETIME NULL,
  `fechaLimite` DATETIME NOT NULL,
  `ponderacion` VARCHAR(45) NOT NULL,
  `puntuacion` INT NOT NULL DEFAULT 0,
  `fkIdUsuarioAsignado` INT NOT NULL,
  `fkIdUsuariocCreador` INT NOT NULL,
  `fkIdProyecto` INT NOT NULL,
  `fkIdDocumento` INT NOT NULL,
  `fkIdtarea` INT NOT NULL,
  PRIMARY KEY (`idtarea`),
  INDEX `fk_tareas_usuarios1_idx` (`fkIdUsuarioAsignado` ASC),
  INDEX `fk_tareas_usuarios2_idx` (`fkIdUsuariocCreador` ASC),
  INDEX `fk_tareas_proyectos1_idx` (`fkIdProyecto` ASC),
  INDEX `fk_tareas_documntos1_idx` (`fkIdDocumento` ASC),
  INDEX `fk_tareas_tareas1_idx` (`fkIdtarea` ASC),
  CONSTRAINT `fk_tareas_usuarios1`
    FOREIGN KEY (`fkIdUsuarioAsignado`)
    REFERENCES `mydb`.`usuarios` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tareas_usuarios2`
    FOREIGN KEY (`fkIdUsuariocCreador`)
    REFERENCES `mydb`.`usuarios` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tareas_proyectos1`
    FOREIGN KEY (`fkIdProyecto`)
    REFERENCES `mydb`.`proyectos` (`idproyecto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tareas_documntos1`
    FOREIGN KEY (`fkIdDocumento`)
    REFERENCES `mydb`.`documntos` (`idDocumento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tareas_tareas1`
    FOREIGN KEY (`fkIdtarea`)
    REFERENCES `mydb`.`tareas` (`idtarea`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`comentarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`comentarios` (
  `idComentario` INT NOT NULL AUTO_INCREMENT,
  `comentario` VARCHAR(255) NOT NULL,
  `fkIdtarea` INT NOT NULL,
  `fkIdUsuario` INT NOT NULL,
  PRIMARY KEY (`idComentario`),
  INDEX `fk_comentarios_tareas_idx` (`fkIdtarea` ASC),
  INDEX `fk_comentarios_usuarios1_idx` (`fkIdUsuario` ASC),
  CONSTRAINT `fk_comentarios_tareas`
    FOREIGN KEY (`fkIdtarea`)
    REFERENCES `mydb`.`tareas` (`idtarea`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comentarios_usuarios1`
    FOREIGN KEY (`fkIdUsuario`)
    REFERENCES `mydb`.`usuarios` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
